# Generated by Django 3.2.17 on 2023-02-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Moshinalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toifa', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Prava toifasi',
                'verbose_name_plural': 'Prava toifalari',
            },
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toifa', models.CharField(max_length=2)),
                ('jins', models.CharField(max_length=5)),
                ('qayerdan', models.CharField(max_length=255)),
                ('vaqt', models.DateTimeField()),
                ('tulov_turi', models.CharField(choices=[('Naqd', 'Naqd'), ('Karta', 'Karta')], default='Naqd', max_length=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('moshina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.car')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='categoriyasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.category'),
        ),
    ]
