# Generated by Django 4.1.7 on 2023-03-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('categoriyasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.category')),
            ],
            options={
                'verbose_name': 'Мошиналар',
                'verbose_name_plural': 'Мошиналар',
            },
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ботнинг хизмат ҳаққи',
                'verbose_name_plural': 'Ботнинг хизмат ҳаққи',
            },
        ),
        migrations.CreateModel(
            name='TextSes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratish', models.CharField(max_length=380)),
                ('jins', models.CharField(max_length=380)),
                ('moshina', models.CharField(max_length=380)),
                ('instructor', models.CharField(max_length=380)),
                ('manzil', models.CharField(max_length=380)),
                ('kun', models.CharField(max_length=380)),
                ('utgan_kun', models.CharField(max_length=380)),
                ('vaqt', models.CharField(max_length=380)),
                ('utgan_vaqt', models.CharField(max_length=380)),
                ('band_qilingan_vaqt', models.CharField(max_length=380)),
                ('tulov', models.CharField(max_length=380)),
                ('mashgulot_yaratilsa', models.CharField(max_length=380)),
                ('mashgulot_yaratilmasa', models.CharField(max_length=380)),
            ],
            options={
                'verbose_name': 'Машғулот техти',
                'verbose_name_plural': 'Машғулот техти',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toifa', models.CharField(max_length=2)),
                ('jins', models.CharField(max_length=5)),
                ('vaqt', models.DateTimeField()),
                ('tulov_turi', models.CharField(choices=[('Нақд', 'Нақд'), ('Карта', 'Карта')], default='Накд', max_length=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='client.client')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='instructor.instructor')),
                ('moshina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.car')),
            ],
            options={
                'verbose_name': 'Машғулотлар',
                'verbose_name_plural': 'Машғулотлар',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='client.category')),
            ],
            options={
                'verbose_name': 'Категориялар нархи',
                'verbose_name_plural': 'Категориялар нархи',
            },
        ),
    ]
