# Generated by Django 4.1.7 on 2023-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tulov_turi',
            field=models.CharField(choices=[('Накд', 'Накд'), ('Карта', 'Карта')], default='Накд', max_length=5),
        ),
    ]
