# Generated by Django 3.2.17 on 2023-02-22 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 12 digits allowed.", regex='^998[378]{2}|9[01345789]\\d{7}$')])),
                ('jins', models.CharField(max_length=5)),
                ('tuman', models.CharField(max_length=255, null=True)),
                ('toifa', models.CharField(max_length=2)),
                ('moshina', models.CharField(max_length=255, null=True)),
                ('nomeri', models.CharField(max_length=11)),
                ('balans', models.PositiveIntegerField(default=0)),
                ('telegram_id', models.BigIntegerField()),
                ('ratet', models.FloatField()),
            ],
            options={
                'ordering': ['-ratet'],
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('client', models.ForeignKey(on_delete=models.SET("o'chib ketgan"), related_name='rating', to='client.client')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='instructor.instructor')),
            ],
        ),
    ]
