# Generated by Django 4.1.7 on 2023-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='latitude',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='longitude',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
