# Generated by Django 4.1.7 on 2023-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dabro',
            field=models.BooleanField(default=False),
        ),
    ]
