# Generated by Django 3.2.17 on 2023-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_ratet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='balans',
            field=models.IntegerField(default=0),
        ),
    ]
