# Generated by Django 4.1.7 on 2023-03-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_latitude_instructor_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='longitude',
        ),
    ]
