# Generated by Django 4.1.7 on 2023-03-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_dabro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='dabro',
            new_name='tasdiqlash',
        ),
    ]
